spring.application.name=smartpark

spring.datasource.url=jdbc:mysql://localhost:3306/smartpark_db
spring.datasource.username=root
spring.datasource.password=Harnoor@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
server.port=8080
